image: jeniceek/debian-ruby

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - apt-cache/
  - .bundle
  - vendor/

services:
  - postgres:latest

variables:
  RAILS_ENV: test
  DB_NAME: lora_test
  RBENV_VERSION: 2.3.1

before_script:
  - sudo apt-get -o dir::cache::archives="$APT_CACHE_DIR" -y install libpq-dev postgresql-client nodejs
  - cp config/database.yml.docker config/database.yml
  - bundle install --path vendor/ --without production --jobs $(nproc) "${FLAGS[@]}"
  - bundle exec rake db:create
  - bundle exec rake db:migrate

test:
  script:
    - bundle exec rspec --color --format documentation --tty
